name: Release docs

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: uv sync
        run: |
          uv sync --only-group docs --no-install-project

      - name: ensure assets
        run: |
          mv assets/images docs/assets/images

      - name: test docs
        run: |
          make docs-test

      - run: uv run mkdocs gh-deploy --force